### ISSUE TITLE
Travis failing 

### ISSUE THREAD

**Issue by FRidh** [python-acoustics/python-acoustics#100]
```py
from acoustics._signal import Signal
    ImportError: No module named 'acoustics._signal'
```

I'm lost as to why it fails. If I create a clean test env in the same way as Travis does, install everything in the same way, and then run the tests I have no problems. To be sure I even tested it in a clean env on a different machine where I checked there were no references to a possible old version of this package. Any ideas what might cause it?

**Comment by FRidh** [comment]
Last time I deleted the top level import but I added that again because I think that's where it should be.

**Comment by felipeacsi** [comment]
This seems to be a cython issue. I don't have experience with cython but I've tried to run the code without  cython installed and I got the same error.

How do you install the acoustics package? I used to install it with `python setup.py develop` but it seems this does not works. I checked the [cython hello world](http://docs.cython.org/src/tutorial/cython_tutorial.html#cython-hello-world) and I installed the package (with the `Signal` import in `__init__.py` commented) and testing using:

    python setup.py build_ext --inplace
    python setup.py install
    >>> from acoustics._signal import Signal

and it works.

Then, I tried to use `pyximport` in `_signal.pyx` (as in the [tutorial](http://docs.cython.org/src/tutorial/cython_tutorial.html#pyximport-cython-compilation-the-easy-way)) which seems to be better and it also works for me without building and install the package (only using `develop`).

I tested this in a clean virtual environment and the installation and tests were sucessfull. I will create a PR showing the changes and we'll see if travis can build.

**Comment by FRidh** [comment]
During development I install it also with `python setup.py develop` and lately I have tested it several times with `python setup.py install` and `pip install .`

`pyximport` is for compiling when importing the module and should be avoided in this case.
`python setup.py build_ext --inplace` I used before I knew `python setup.py develop`, I also manually maintained a `.pth` file in those days :-)

If you look at the log you can see that Cython works; the `_setup.pyx` is converted to `c`, which is then compiled and finally moved into the egg:

```
copying build/lib.linux-x86_64-3.4/acoustics/_signal.cpython-34m.so -> build/bdist.linux-x86_64/egg/acoustics
```

**Comment by FRidh** [comment]
Okay, I now also get the import error when trying to import `acoustics`. Something was wrong before then. But nevertheless, the building goes fine, and the files are there after installation. There is just no way in accessing the module...

**Comment by FRidh** [comment]
Travis uses `python setup develop` for now (#101) until we found a fix for this issue.

**Comment by felipeacsi** [comment]
Checkout [this](http://docs.astropy.org/en/v0.4.3/development/testguide.html#id4)

> To test any compiled C/Cython extensions, you must run `python setup.py develop` prior to running the py.test command-line script. Otherwise, any tests that make use of these extensions will not succeed.

So, I think we're right with the travis configuration.

**Comment by FRidh** [comment]
We looked again at the problem in #106 and all seems to work just fine...
