### ISSUE TITLE
py.test has importerrors on Python 2.7

### ISSUE THREAD

**Issue by FRidh** [python-acoustics/python-acoustics#163]
For some time now, when running `python setup.py test` on Python 2.7, pytest cannot import several modules of its own. 

Looking at travis, it seems to have started to happen since pytest 2.7.2 was used.

**Comment by FRidh** [comment]
Still okay at 800fc33
Problem since 132a7d6

Downgrading to `pytest=2.7.1` (along with package `py`) didn't make a difference though.
Downgrading to `setuptools=17` neither.

Any ideas @felipeacsi ?

**Comment by felipeacsi** [comment]
I don't see any problem with pytest in build [348](https://travis-ci.org/python-acoustics/python-acoustics/builds/70867714) after https://github.com/python-acoustics/python-acoustics/commit/132a7d65f47db50bde4376535eda101eba08d41a

What I can see after the importerrors is that there are always syntax errors. For example in travis job [389.1](https://travis-ci.org/python-acoustics/python-acoustics/jobs/74582560) there is a problem using `yield from` which [were introduced in python 3.3](https://docs.python.org/3/whatsnew/3.3.html). Perhaps you can handle this using six or other alternative. In [389.2](https://travis-ci.org/python-acoustics/python-acoustics/jobs/74582561) there are other issues. Looking at other jobs there are similar errors so hopefully is a "simple" thing.

I hope that helps. Let me know if you can resolve this issue.

**Comment by FRidh** [comment]
Those builds you refer to are for PR #169 , which is indeed Python 3.4 only for now. Yes, I can easily get rid of the `yield from` and make it compatible with the other versions.

Looking at the builds https://travis-ci.org/python-acoustics/python-acoustics/builds
There were some errors which I fixed, but still there is an issue that pytest for Python 2.7 can't import certain modules.
https://travis-ci.org/python-acoustics/python-acoustics/jobs/70867743
```
==================================== ERRORS ====================================
____ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_commands.py _____
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_commands.py:41: in <module>
    from testtools import content
E   ImportError: No module named testtools
______ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_core.py _______
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_core.py:45: in <module>
    import fixtures
E   ImportError: No module named fixtures
______ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_files.py ______
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_files.py:20: in <module>
    import fixtures
E   ImportError: No module named fixtures
______ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_hooks.py ______
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_hooks.py:44: in <module>
    from testtools.content import text_content
E   ImportError: No module named testtools.content
___ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_integration.py ___
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_integration.py:17: in <module>
    import fixtures
E   ImportError: No module named fixtures
____ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_packaging.py ____
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_packaging.py:47: in <module>
    import fixtures
E   ImportError: No module named fixtures
______ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_setup.py ______
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_setup.py:30: in <module>
    import fixtures
E   ImportError: No module named fixtures
______ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_util.py _______
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_util.py:20: in <module>
    import testscenarios
E   ImportError: No module named testscenarios
_____ ERROR collecting .eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_version.py _____
.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/test_version.py:18: in <module>
    from testtools import matchers
E   ImportError: No module named testtools
==================== 312 passed, 9 error in 159.72 seconds =====================
```

**Comment by felipeacsi** [comment]
pytest was trying to discover tests in `.eggs` folder so it discover `.eggs/pbr-1.3.0-py2.7.egg/pbr/tests/*`. I've added `.eggs` to ignored folders for pytest and the issue is gone.
