### ISSUE TITLE
Typo in installation instructions

### ISSUE THREAD

**Issue by wengertj** [python-acoustics/python-acoustics#204]
Hey guys,

I  think you have a typo in the readme:
```pip install streaming``` is probably the wrong command to install this library :smile: 

Keep up the great work!
Jo

**Comment by FRidh** [comment]
whoops, thanks for reporting. I was unifying the `README`'s of projects I was publishing on PyPI and then it must have slipped in.

**Comment by FRidh** [comment]
Fixed with 9bdd3c9a92777fd1736af806c267a10066c039e4
