### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by kxuanCeltik** [python-acoustics/python-acoustics#205]
Hi collegues,

I'm not developer, sorry for open an issue for for the documentation.

Please, place this topic in it site.

I want help to improve that documentation.

Maybe in github page? or in read the docs?

Thanks and sorry,

Regards

**Comment by topherbuckley** [comment]
@FRidh may I suggest closing this? Not really any specific issue and I'm trying to go through the list.
