### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by topherbuckley** [python-acoustics/python-acoustics#208]
Upon installing via pip, I received an error stating that I was missing a "vcvarsall.bat" file. Note error #203 does not seem to apply as I already have both numpy and cython installed.  

See full log below:

`$ pip install acoustics
Collecting acoustics
  Downloading acoustics-0.1.2.tar.gz (178kB)
Requirement already satisfied: numpy>=1.8 in f:\software\anaconda34\lib\site-packages (from acoustics)
Requirement already satisfied: scipy>=0.16 in f:\software\anaconda34\lib\site-packages (from acoustics)
Requirement already satisfied: matplotlib in f:\software\anaconda34\lib\site-packages (from acoustics)
Requirement already satisfied: six>=1.4.1 in f:\software\anaconda34\lib\site-packages (from acoustics)
Requirement already satisfied: cython in f:\software\anaconda34\lib\site-packages (from acoustics)
Requirement already satisfied: pandas>=0.15 in f:\software\anaconda34\lib\site-packages (from acoustics)
Collecting tabulate (from acoustics)
  Downloading tabulate-0.7.7-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil in f:\software\anaconda34\lib\site-packages (from matplotlib->acoustics)
Requirement already satisfied: pytz in f:\software\anaconda34\lib\site-packages (from matplotlib->acoustics)
Requirement already satisfied: cycler in f:\software\anaconda34\lib\site-packages (from matplotlib->acoustics)
Requirement already satisfied: pyparsing!=2.0.4,>=1.5.6 in f:\software\anaconda34\lib\site-packages (from matplotlib->acoustics)
Building wheels for collected packages: acoustics
  Running setup.py bdist_wheel for acoustics: started
  Running setup.py bdist_wheel for acoustics: finished with status 'error'
  Complete output from command f:\software\anaconda34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-build-celfs_q0\\acoustics\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\CHRIST~1\AppData\Local\Temp\tmpqi49pa9dpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\acoustics
  copying acoustics\aio.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\ambisonics.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\atmosphere.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\bands.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\building.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\cepstrum.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\criterion.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\decibel.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\descriptors.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\directivity.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\doppler.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\generator.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\imaging.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\octave.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\power.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\quantity.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\reflection.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\room.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\signal.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\utils.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\weighting.py -> build\lib.win-amd64-3.5\acoustics
  copying acoustics\__init__.py -> build\lib.win-amd64-3.5\acoustics
  creating build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\iec_61260_1_2014.py -> build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\iec_61672_1_2013.py -> build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\iso_1683_2015.py -> build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\iso_1996_1_2003.py -> build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\iso_1996_2_2007.py -> build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\iso_9613_1_1993.py -> build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\iso_tr_25417_2007.py -> build\lib.win-amd64-3.5\acoustics\standards
  copying acoustics\standards\__init__.py -> build\lib.win-amd64-3.5\acoustics\standards
  creating build\lib.win-amd64-3.5\acoustics\data
  copying acoustics\data\iec_61672_1_2013.csv -> build\lib.win-amd64-3.5\acoustics\data
  running build_ext
  building 'acoustics._signal' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for acoustics
  Running setup.py clean for acoustics
Failed to build acoustics
Installing collected packages: tabulate, acoustics
  Running setup.py install for acoustics: started
    Running setup.py install for acoustics: finished with status 'error'
    Complete output from command f:\software\anaconda34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-build-celfs_q0\\acoustics\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\CHRIST~1\AppData\Local\Temp\pip-xt_vu1c9-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\acoustics
    copying acoustics\aio.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\ambisonics.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\atmosphere.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\bands.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\building.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\cepstrum.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\criterion.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\decibel.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\descriptors.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\directivity.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\doppler.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\generator.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\imaging.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\octave.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\power.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\quantity.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\reflection.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\room.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\signal.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\utils.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\weighting.py -> build\lib.win-amd64-3.5\acoustics
    copying acoustics\__init__.py -> build\lib.win-amd64-3.5\acoustics
    creating build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\iec_61260_1_2014.py -> build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\iec_61672_1_2013.py -> build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\iso_1683_2015.py -> build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\iso_1996_1_2003.py -> build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\iso_1996_2_2007.py -> build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\iso_9613_1_1993.py -> build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\iso_tr_25417_2007.py -> build\lib.win-amd64-3.5\acoustics\standards
    copying acoustics\standards\__init__.py -> build\lib.win-amd64-3.5\acoustics\standards
    creating build\lib.win-amd64-3.5\acoustics\data
    copying acoustics\data\iec_61672_1_2013.csv -> build\lib.win-amd64-3.5\acoustics\data
    running build_ext
    building 'acoustics._signal' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "f:\software\anaconda34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\CHRIST~1\\AppData\\Local\\Temp\\pip-build-celfs_q0\\acoustics\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\CHRIST~1\AppData\Local\Temp\pip-xt_vu1c9-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\CHRIST~1\AppData\Local\Temp\pip-build-celfs_q0\acoustics\
`

**Comment by FRidh** [comment]
In order to install this package from source, Cython is needed, but Cython will need a C++ compiler.
Please see the following document.
https://github.com/cython/cython/wiki/CythonExtensionsOnWindows
