### ISSUE TITLE
data not squared prior to being exponentially time weighted in iec_61672_1_2013.py

### ISSUE THREAD

**Issue by topherbuckley** [python-acoustics/python-acoustics#213]
Currently at line 169:

       return lfilter(b, a, data)[...,n-1] / integration_time # Perform the integration. Select the final value of the integration.

The exponential time weighting filtering is performed before the data is squared. I'm not sure if this would have an effect or not since if you square a weighted negative level later it should turn out to be the same positive weighted level after squaring, but according to the [standard](https://archive.org/stream/gov.in.is.15575.1.2005/is.15575.1.2005#page/n7/mode/2up) (page 3 Fig 1) the squaring operation should occur first. @duracell013 maybe you want to weigh in on this? Any reason you see the need to square the signal first? Or is this fine? If left as is, it allows the squaring to occur elsewhere and likely save some processing speed/memory.

**Comment by FRidh** [comment]
The `pressure` parameter of `integrate` takes pressure squared so it is done already:
https://github.com/python-acoustics/python-acoustics/blob/5bd929186e0eed4c2885dd79f3c3afccf39289f4/acoustics/standards/iec_61672_1_2013.py#L147
