### ISSUE TITLE
signal.py example name collision with core python library

### ISSUE THREAD

**Issue by Ashymad** [python-acoustics/python-acoustics#214]
The example signal.py filename collides with core python library 'signal' which causes many problems when you cd in to the directory, for example ipython does not even start.

**Comment by Ashymad** [comment]
It seems that only ipython3 crashes, ipython runs fine. I think the file should be renamed, as this issue can cause headaches for someone trying out the library with these examples.

**Comment by FRidh** [comment]
We can prefix the examples with `example_`.

**Comment by felipeacsi** [comment]
Done in https://github.com/python-acoustics/python-acoustics/pull/215. Thank you @Ashymad!
