### ISSUE TITLE
Signal.duration using integer division

### ISSUE THREAD

**Issue by nicolas-f** [python-acoustics/python-acoustics#217]
Hi,

I don't know if it is intended but signal.duration() return an integer.
https://github.com/python-acoustics/python-acoustics/blob/master/acoustics/_signal.pyx#L95

You should convert sample rate to double in order to return the duration with milliseconds.

**Comment by FRidh** [comment]
If both `samples` and `fs` are integers, and you are using Python 2.7, then you will indeed get floor division.

We should use `from future import division`.

**Comment by FRidh** [comment]
Support for Python 2.7 has been dropped, so this won't cause any trouble anymore. Even so, I explicitly call `float` on it now because it should always be a float.
