### ISSUE TITLE
No such file or directory: /data/iec_61672_1_2013.csv

### ISSUE THREAD

**Issue by 742617000027** [python-acoustics/python-acoustics#226]
Hey, I'm getting this error when I try to `import acoustics`, since the iec_61672_1_2013.csv seems to be missing (the whole dir that should contain it, rather):

> import acoustics
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/acoustics/__init__.py", line 10, in <module>
>     import acoustics.atmosphere
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/acoustics/atmosphere.py", line 39, in <module>
>     from acoustics.standards.iso_9613_1_1993 import *  # pylint: disable=wildcard-import
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/acoustics/standards/__init__.py", line 24, in <module>
>     from acoustics.standards import (
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/acoustics/standards/iec_61672_1_2013.py", line 43, in <module>
>     io.BytesIO(pkgutil.get_data('acoustics', os.path.join('data', 'iec_61672_1_2013.csv'))), sep=',', index_col=0)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py", line 637, in get_data
>     return loader.get_data(resource_name)
>   File "<frozen importlib._bootstrap_external>", line 916, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/acoustics/data/iec_61672_1_2013.csv'

Installed the package via pip. Any help or fix would be much appreciated!

**Comment by 742617000027** [comment]
Created the folder and placed the file in there manually, that fixed the issue.

**Comment by FRidh** [comment]
What version of the package is this?

**Comment by felipeacsi** [comment]
I can confirm this on a new virtual environment. The version is `acoustics-0.2.0.post1`.

**Comment by 742617000027** [comment]
`acoustics-0.2.0.post1` for me as well.

**Comment by FRidh** [comment]
Need to fix how we use `MANIFEST.in` and `package_data`. The former is for files that need to be included in the `sdist`, and the latter for files that need to be installed. In the CI I will let it generate an `sdist` first, and then let it build a wheel and install it. That way, we should cover the whole cycle.

**Comment by FRidh** [comment]
Fixed in 0.2.0.post2
