### ISSUE TITLE
automatic amplitude normalization at wav reading

### ISSUE THREAD

**Issue by apatlpo** [python-acoustics/python-acoustics#229]
Hi,

wav amplitudes are automatically normalized according to:

https://github.com/python-acoustics/python-acoustics/blob/87e8b805bde1dfbc3bd18eb35d35c18066bf6292/acoustics/_signal.py#L1040

Couldn't this become an option (with normalization as default) that could be turned off?

I am in a situation where I'd need to keep original amplitudes.

**Comment by a-stepien** [comment]
https://github.com/python-acoustics/python-acoustics/pull/221#discussion_r240001923

**Comment by FRidh** [comment]
Fixed in 19cde29e1f8a2a4f695893eadd3a64538c4d808e. Released in 0.2.3.
