### ISSUE TITLE
Digital filter critical frequencies must be 0 < Wn < 1 using the t60_impulse function in room.py

### ISSUE THREAD

**Issue by pranaymanocha** [python-acoustics/python-acoustics#230]
Hi,
I was using this t60_impulse() function in room.py and encountered this error "ValueError: Digital filter critical frequencies must be 0 < Wn < 1". I use a wav file as an impulse response with octave frequency bands. 
Thanks!

**Comment by FRidh** [comment]
Can't do much without an example along with stack strace.
