### ISSUE TITLE
what is the scale obtain from `third_octaves` function?

### ISSUE THREAD

**Issue by masalinas** [python-acoustics/python-acoustics#233]
I'm using the third_octave for a velocity temporal series, the level of this array are like:

x: 1Hz, y: 0,01 mm/s
x:1,5Hz, y:0.05 mm/s

But when obtain the new temporal series from third octave procedure i obtain:

x: 1Hz, y: 50,3
x: 1.5Hz, y: 44,7

And I must obtin values from 0,01 to 0,09 mm/s

The question what is the scale created from this method?

**Comment by FRidh** [comment]
Please provide a minimum working example.

**Comment by FRidh** [comment]
No response, closing.
