### ISSUE TITLE
New room acoustic parameters

### ISSUE THREAD

**Issue by martin-louazel-engineering** [python-acoustics/python-acoustics#235]
Hi,

I recently worked on a project for room acoustic parameters calculations in Python. Thus, if you want, I would be glad to contribute to your project.

I worked mainly on the following parameters (mostly taken from the ISO 3382) :
-Reverberation time computed by interruption of a pink noise signal
-Cte (Clarity/Clarheitsmass) generalized version of the C80 (or C50) considering te miliseconds.
-Dte (Definition/Deutlichkeit)
-Ts (Center time) Used in a similar fashion to know about the reverberation and clarity of the room (signal's "center of gravity")
-STearly (early support stage) mostly used on a performing stage to measure how performers can hear themselves/other performers
-STlate (late support stage) same, but for late reverberance
-STtotal (total support stage) same, but for total reverberance
-EEL (early ensemble level) same, but taken from recent scientifc litterature (not in the ISO 3382, and still in discussion whereas it is useful or not)
-And other parameters computed with 2 signals (strength G, Early lateral energy fraction Jlf and Jlfc, inter-aural cross correlation coefficient IACC)

However, I am still new to the whole "GitHub contribution" thing, so I would probably need some help on how to contribute correctly to make sure I don't do any mistakes.

Please tell me if you are interested in this.
Have a great day.
Martin

**Comment by FRidh** [comment]
Hi,

It's nice to hear you're interesting in contributing. I think it would be really nice to add those features, however, i just do not have the time to work on this library anymore and supporting you with this.

**Comment by martin-louazel-engineering** [comment]
Thanks for your reply.

It's ok, I understand. I'll try my best to work on this on my own, and I'll just create a pull request if I come up with anything decent.

Wish you all the best.
Martin

**Comment by felipeacsi** [comment]
Martin,

feel free to contact me in private (my username at gmail) or by opening an issue.
