### ISSUE TITLE
24 bits wav support

### ISSUE THREAD

**Issue by adri123** [python-acoustics/python-acoustics#237]
Hello,
What method do you recommand to open 24 bits wav files with python-acoustics library ?
As today scipy still does'nt support this bitrate.
I've read topics and issues about this, but I still not understand the best support to use.
Thanks for your work.

**Comment by DanKremer** [comment]
I traditionally use [pysoundfile](https://pypi.org/project/SoundFile/). I remember seeing a ticket for adding this sometime in the past, not sure where it ended.

**Comment by FRidh** [comment]
Related PR https://github.com/python-acoustics/python-acoustics/pull/221

**Comment by FRidh** [comment]
Rebased in #238.

**Comment by adri123** [comment]
Thanks for your reply.
I saw that the modification appears in this version : https://github.com/python-acoustics/python-acoustics/tree/9c7d9103fb4e3ec9acbaefedfefea3aa37ae1a4c
But I'm unable to try this version as I'm a real newby in github and installing a specific version in a test environnement of Python.
Can you provide me some help ? (some links to tutos / howto are really welcome to)
My goal at the end will be to contribute. Can you explain me how do work in a simple way ?
Thanks in advance.

**Comment by kxuanCeltik** [comment]
Hi adri,

You can probe if this command update the package if you have a global
installation:

Proof this way:

sudo pip install
https://github.com/python-acoustics/python-acoustics/archive/v0.2.3.tar.gz

OR take a look of:

https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

Happy coding !!!

**Comment by adri123** [comment]
Thanks. so, I tryed :

`(base) C:\Users\XXX>pip install git+git://github.com/python-acoustics/python-acoustics.git@9c7d9103fb4e3ec9acbaefedfefea3aa37ae1a4c`

The output is : 
```
Collecting git+git://github.com/python-acoustics/python-acoustics.git@9c7d9103fb4e3ec9acbaefedfefea3aa37ae1a4c
  Cloning git://github.com/python-acoustics/python-acoustics.git (to revision 9c7d9103fb4e3ec9acbaefedfefea3aa37ae1a4c) to c:\users\XXX\appdata\local\temp\pip-req-build-h_exx5sc
  Running command git clone -q git://github.com/python-acoustics/python-acoustics.git 'C:\Users\XXX\AppData\Local\Temp\pip-req-build-h_exx5sc'
  Running command git checkout -q 9c7d9103fb4e3ec9acbaefedfefea3aa37ae1a4c
  fatal: reference is not a tree: 9c7d9103fb4e3ec9acbaefedfefea3aa37ae1a4c
ERROR: Command errored out with exit status 128: git checkout -q 9c7d9103fb4e3ec9acbaefedfefea3aa37ae1a4c Check the logs for full command output.
```

I cannot install the branch that I'm interressed to.
Sorry to be boring ! Any help ?

**Comment by adrian-stepien** [comment]
I guess this can be closed now?

**Comment by felipeacsi** [comment]
Yes, thanks @adrian-stepien.

@adri123 I don't know if you resolved this but you can try with `pip install https://github.com/python-acoustics/python-acoustics/archive/v0.2.3.tar.gz` as said previously. If you have any questions, please mention me.
