### ISSUE TITLE
What is the role of integrate_bands in third_octaves?

### ISSUE THREAD

**Issue by ChanonTonmai** [python-acoustics/python-acoustics#244]
Hello guys

Now I am doing sound analysis with 1/3 octave analysis. So, I test with this third_octaves function. Then I see that the function third_octaves has a speed bottleneck at the integrate_bands function. So, I want to know that what is the role of integrate_band. Perhaps, I will build a new function which can speed up this function by using estimation method something like that. 

Are there any solution that can integrate band instead of using integrate_band function? 

Thank you
K. Chanon

**Comment by tcanders** [comment]
Hi there, the input to third_octaves is a power spectrum in the form of FFT bins on a linear frequency axis. integrate_band appears to take all the bins within each third-octave range and sum them. In other words, it "integrates" the energy across third-octave band ranges of frequency.

**Comment by ChanonTonmai** [comment]
Thanks for answer

It's mean that this function do the integrate in spectrum domain right? Then is that possible to estimate the value of the amplitude by using the sum of 5 (or more) highest value between the 1/3 octave frequency to get faster. Moreover, I am curious that if we find this value using time domain analysis. Is that will be faster? I ask this because I think the FFT is time consume algorithm.

**Comment by FRidh** [comment]
Fastest method is to use 1/3-octave band pass filters and integrating per band the result. 
```py
import numpy as np
import acoustics

fs = 44100
duration = 10
signal = acoustics.Signal(np.random.randn(duration*fs), fs=fs)
frequencies, octaves = signal.third_octaves()
levels = octaves.leq()
```

**Comment by ChanonTonmai** [comment]
Thanks
