### ISSUE TITLE
dbsum a list

### ISSUE THREAD

**Issue by zoner72** [python-acoustics/python-acoustics#250]
Hi

I was curious if there is an easy way to dbsum pandas columns with spectral data.
this might be a very rookie question....

sum_result = dbsum(df.loc[:,'LAeq 25Hz':'LAeq 500Hz'])

kind regards
zoner

**Comment by felipeacsi** [comment]
Hello,

do you want to use `dbsum` per frequency band, right? In that case you need to indicate in what axis are you performing the sum (in this case, `axis=0`).

Here you have an example:

```
import pandas as pd
df = pd.DataFrame({"LAeq 25Hz": [20, 20], "LAeq 500Hz": [30, 30]})
sum_result = dbsum(df.loc[:,'LAeq 25Hz':'LAeq 500Hz'], axis=0)
```

Then, the value of `sum_result` is `array([23.01029996, 33.01029996])`. It does not contain the column names but it works.

Does this solve your problem?

**Comment by zoner72** [comment]
That's exactly what my brain was thinking but I didn't ask correctly 😁. Thanks for that, really appreciate it
