### ISSUE TITLE
Possible formula inaccuracies for ISO 9613-1:1993?

### ISSUE THREAD

**Issue by ethindp** [python-acoustics/python-acoustics#256]
I haven't read the standard in question, but looking at the code I've noticed what I think might be either a documentation bug or a bug in the code itself. In standards.iso_9613_1_1993, the formula for calculating `c`, given `T_0` and `T`, is written as `c=343.2(T/T_0)`, but the formula in code is given as `c=343.2sqrt(T/T_0)`. Is the documentation wrong, or is the code wrong? As I said I haven't read the actual standard, so for all I know this is correct, but I thought I'd point out this small deficiency.

**Comment by Moosevellous** [comment]
![image](https://user-images.githubusercontent.com/29476764/151883851-d1517067-b23f-4f1b-b696-7d96f4d6728b.png)
The standard includes a tricky 'to the power half' at the end, so the code version is correct after all.

**Comment by ethindp** [comment]
Oh, okay, I was wondering about that. Perhaps a note about that should be added in the documentation just in case.
